name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create .env
      run: cp .env.example .env
    - name: Create .test.env
      run: cp .test.env.example .test.env
    - name: Create pems
      run: go run .tools/rsa/keygen.go
    - name: Build docker images
      run: docker-compose build
    - name: Run docker images
      run: docker-compose up -d
    - name: Run tests
      run: docker exec -t goserver go test -v ./...
    - name: Clean up
      if: success() || failure()
      run: docker-compose down --rmi all -v --remove-orphans